// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@shared/supabase.types';

// Use remote database for hybrid approach (local frontend + remote backend)
const SUPABASE_URL = "https://rpgpwailndlmpgufmfzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "REDACTED_SECRET";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});