// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use remote database for hybrid approach (local frontend + remote backend)
const SUPABASE_URL = "https://rpgpwailndlmpgufmfzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ3B3YWlsbmRsbXBndWZtZnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQ3NzYsImV4cCI6MjA2OTEzMDc3Nn0.EjnuLcjM9Kf9UAX4762nGVMoC-KK1U-ydmypPsfrJs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});