// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@shared/supabase.types';

// Use local development URLs when in development mode
const isDevelopment = import.meta.env.DEV;

const SUPABASE_URL = isDevelopment 
  ? "http://127.0.0.1:54321" 
  : "https://rpgpwailndlmpgufmfzi.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = isDevelopment
  ? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ3B3YWlsbmRsbXBndWZtZnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTQ3NzYsImV4cCI6MjA2OTEzMDc3Nn0.EjnuLcjM9Kf9UAX4762nGVMoC-KK1U-ydmypPsfrJs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});